### ISSUE TITLE
.NET Core 2 version?

### ISSUE THREAD

**Issue by goofballLogic** [auth0-samples/aspnet-core-mvc-plus-webapi#1]
Would it be possible to upgrade this sample to use the new configuration API in .NET Core 2?

**Comment by jerriep** [comment]
@goofballLogic This is an outdated sample. Up to date samples are at https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples

**Comment by goofballLogic** [comment]
Ok thanks @jerriep  . We're specifically looking for the .NET Core 2 equivalent of having both token-based and cookie-based authentication (which this old example covers). We're having trouble tracking that down in your documentation.

**Comment by nicosabena** [comment]
I just updated the sample to .Net Core 2 (the `v1` branch still contains the old code).
